dist: xenial
language: python
python:
- '3.7'
script:
- python setup.py test
deploy:
  provider: pypi
  user: __token__
  on:
    tags: true
  password:
    secure: MnaDdO/rHQrdBoAue24w95g6EPD736/bkH+Bb2xXlrwjsfPd5Y19xRWK6nDd3w141n9iBd1xxV9Lp2yr+qVQqpAa2uOZO9L8M3uviIBCazImHw6huAAVPICfPjlmq4AAtGmZPGFmdEKMswagxAyGrpuig/HmcaybSJ8iBElISqMQut6Lxdp/KXVbvgcsLkJR08lhE+lF5nSmkhYMqepcZ0tyvkFhyS/009CgNDmcYVnPDITvwl0HPiGqY/Bj1/1obNovdp/jv7+hKhzajI+zorDCLf5iXMDLmKUnj+oTMwpmJG64sfihugkPFoYfEU1vNi2J1/hMrixCTnM/aBqGVKQt8bWjD1DiIuMl+1PnEnpCx9T3zyG4BrOdwmRGQ/ALf31mfPEDB4b/ZcVjOEXQCa1YDssWWU2cQYn3b9MycsGCD9fUwR/IvU106PEjs3W8LP7F0lATdz+Mp2lURdNwNgkfhg6/3Wes7PVQfBtQxzK1jV/RPwBPOKcXMA1gPfyQhLXNPOVz0xPyxWWHwbILs9PAT4TwoiCdUwhYXa/CTwZrMtIjNSLRHAp8hRbeqpQd07eUm91CH2Z2JdSfMxCXLlWMp1NE4VCQaX9UQsBwPQ40cpIoF4iGl3KFu7Vl+pWhZvy7sVHJ36PpcuhbiX0sMm1LI/6Xoy7TUDIcZ/xC1Vw=
